  default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  development:
    <<: *default
    database: onejob_development

  test:
    <<: *default
    database: onejob_test

  production:
    <<: *default
    database: onejob_production
    username: onejob
    password: <%= ENV['ONEJOB_DATABASE_PASSWORD'] %>
